### PR TITLE
add support for index hints in Update statement for MySQL

### PR DESCRIPTION
**Pull request by joeqiao1984**
- add support for index hints in update statment for mysql

- Documentation: 
https://dev.mysql.com/doc/refman/8.0/en/update.html
https://dev.mysql.com/doc/refman/8.0/en/select.html
https://dev.mysql.com/doc/refman/8.0/en/join.html

- Example sql:
```sql
UPDATE demo FORCE INDEX (idx_demo) SET col1 = NULL WHERE col2 = 1
```

### CODE REVIEW

**Comment by manticore-projects** [comment]
Greetings!

Thank you for your contribution. Although I have some concerns.
Please have a look at https://manticore-projects.com/JSQLParser/contribution.html#amend-the-code for some tips, on how to craft PRs.

**Comment by joeqiao1984** [comment]
Thanks for the review, I will look into it

**Comment by manticore-projects** [comment]
Is that still relevant? Otherwise I would close this eventually.

**Comment by manticore-projects** [comment]
Any feedback please? I would like top close this otherwise.

**Pull request merged**
