### PR TITLE
feat: Add support for `REFRESH MATERIALIZED VIEW`

### PR DESCRIPTION
**Pull request by jxnu-liguobin**
closed https://github.com/JSQLParser/JSqlParser/issues/1692

### CODE REVIEW

**Comment by manticore-projects** [comment]
Greetings! Thank your for your contribution and welcome to the JSQLParser team.

**Comment by manticore-projects** [comment]
You added new Tokens and so you will need to update the Keywords as described here: https://manticore-projects.com/JSQLParser/contribution.html#manage-reserved-keywords

**Comment by jxnu-liguobin** [comment]
> You added new Tokens and so you will need to update the Keywords as described here: https://manticore-projects.com/JSQLParser/contribution.html#manage-reserved-keywords
> 
> Also you will need to synchronize against latest commit since I amended the Grammar. Sorry for this hassle, there was no better way to incorporate needed corrections.

I modified the PR, how about it?

**Comment by manticore-projects** [comment]
> I modified the PR, how about it?

Kudos, very nicely done! Thank you for your contribution and look forward seeing more PRs from you soon.

**Comment by jxnu-liguobin** [comment]
> > I modified the PR, how about it?
> 
> Kudos, very nicely done! Thank you for your contribution and look forward seeing more PRs from you soon.

Thank you, when is the next version expected to be released?

**Comment by manticore-projects** [comment]
> Thank you, when is the next version expected to be released?
@wumpz: I think we have the perfect material for a smooth End of Year Release, please consider a `mvn publish` as soon as you can.

**Pull request merged**
