### PR TITLE
Pull request for two changes needed for the integration of JSqlParser in SQuirreL SQL

### PR DESCRIPTION
**Pull request by gerdwagner**
Hi,

thanks for your great work on JSqlParser.

I just uploaded a new snapshot version of SQuirreL SQL client http://www.squirrelsql.org that replaces its former parser by JSqlParser, see 
https://sourceforge.net/projects/squirrel-sql/files/3-snapshots/snapshot-20190711_2226/

There were two things I needed, which are included in this pull request.

One more feature that would be nice but that I found a workaround for is if TablesNamesFinder would have a getter for Table objects instead of table names only.

Thanks again
Gerd

### CODE REVIEW

**Comment by wumpz** [comment]
I added some review comments. 

Thx for using and improving JSqlParser.

**Comment by wumpz** [comment]
The problem with **getTables** is, that the result of **TableNamesFinder** would change in a way, (duplicates). There could be the same table name for two different **Table** instances. I think the right way to tackle this is to override **protected String extractTableName(Table table)** and collect it by your own, or the internal structure of TableNameFinder should be modified to something like Map<String, List<Table>> where hash key is the fully qualified table name.

**Comment by wumpz** [comment]
Any progress here?

**Comment by gerdwagner** [comment]
Hm, probably closing the request wasn't the right choice.

I request want my changes to be merged. 
If there's something I've got to do please let me know.

**Comment by wumpz** [comment]
I changed the two lines from your PR by hand. So we can close this PR. Thx for using JSqlParser.

**Pull request closed without merging**
