### PR TITLE
Add Upsert Grammer

### PR DESCRIPTION
**Pull request by messfish**
Greetings. Right now I am interestead in reading documents related to phoneix SQL so I want to see what I could contribute from it. It seems there is no "upsert" involved in the parser. So I write the
implementation of "Upsert" and several basic test cases.

### CODE REVIEW

**Comment by wumpz** [comment]
How do you explain this coverage descreasing by 1.6 percent? That is quite a bit.

**Comment by messfish** [comment]
How about this time? I think mainly because I failed to add test cases for the DeParser code.

**Comment by wumpz** [comment]
Better instead of 1.6 now 0.8 percent. Dont you see all coveralls statistics within your pull request? I thought this is public.

**Comment by messfish** [comment]
All right Tobias, I finally get rid of the code coverage problem and everything works fine for me. Now can you look into my pull request?

**Comment by wumpz** [comment]
Thx for the effort. I merged it already.

**Pull request merged**
