### PR TITLE
Array literal

### PR DESCRIPTION
**Pull request by opeongo**
This pull request implements the Postgres SQL ARRAY literal, and the ANY and ALL array operators.

### CODE REVIEW

**Comment by wumpz** [comment]
I will look into it. At the moment I am nearly full time offline. You know holidays.  :) Cheers Tobias

**Comment by opeongo** [comment]
Hi Tobias,

I'm just wondering if you have any interest in this feature, or is it a
dead end?

**Comment by wumpz** [comment]
Sorry. I overlooked your pr after beeing back from holidays. 

What I do not like about your change is this kind of token "array whitespace* [". I have to admit, that I do not have a proper solution at hand. Thats the reason your pr is not merged. At the moment I do not think, that a "correct" (in my eyes ;)) solution and the "bracket" quotation of identifiers can coexist. Maybe one could construct a solution using syntactic or token lookahead .. Tobias

**Comment by opeongo** [comment]
I agree that it would be aesthetically more pleasing if token did not use
the '[' character, but I was not able to figure out how to do it
otherwise.  I have a limited experience in developing parsers and I don't
fully understand all of the more advanced features of javacc.  Can you give
me a more specific suggestion to try out, or can you point me to some
sample code that deals with a similar problem?  If I had an avenue to
explore I would give it another go.

**Comment by opeongo** [comment]
I did some more work with javacc and lexical states for another project, and learned a bit ore how to use them.  I have updated my code so that it uses a lexical state change instead of the  "array whitespace* [" idiom.

Unfortunately I am a bit github challenged and I was not able to merge your master in to my development tree so that I could sort out the conflicts.  My changes are based on a version of your code that I checked out in the summer, and it appears to have conflicts.  Sorry about that.

**Comment by opeongo** [comment]
Oops, I did not mean to close the pull request.

**Comment by opeongo** [comment]
Hi Tobias

Is there anything I can do to move this along?  Is is a matter of me not getting a clean pull request together, or is the solution still not right?

**Comment by wumpz** [comment]
Your corrected solution looks more promising. I did not see a single test. Please add some and I will do the merge and coflict resolving. Cheers Tobias

**Comment by wumpz** [comment]
This PR has come a long way. 

Two points from me: first of all I merge PRs using githubs merge & squash. So if you want to control the commit you should squash it by yourself. Second, could you upgrade your PR to the actual SNAPSHOT. There were some API changes that seem to collide with your changes.

**Comment by tserr** [comment]
Hi @opeongo, I tried to rebase your PR to the current SNAPSHOT (5896d8387bde6cd0cf822a67354954c046bf1864) and added the feature to use "ARRAY[...]" as PrimaryExpression (to use it as SelectItem). You find both patches attached ([array-as-PrimaryExpression.patch.zip](https://github.com/JSQLParser/JSqlParser/files/1344531/array-as-PrimaryExpression.patch.zip)).

The file rebase-to-5896d8387bde6cd0cf822a67354954c046bf1864.patch contains your PR (based on SNAPSHOT). The file array-as-PrimaryExpression.patch contains my feature extension.

Is there anything else I can do to help getting this feature merged?

**Comment by wumpz** [comment]
should work now with removal of sqlserver bracket quotation

**Pull request closed without merging**
