### PR TITLE
Fix issue #452

### PR DESCRIPTION
**Pull request by chrycheng**
Fixes issue #452.  I basically moved the logic of `AnalyticExpression`'s `toString` to `visit(AnalyticExpression)` in `ExpressionDeParser` and replaced most calls to `toString` on the components to calls to `accept`.  I also introduced a few members that I think were required in order to be able to test the fix.  I limited the access to the package level to stress the fact that they are internal-only.  I hope you don't mind I also organized the imports on the existing classes.

### CODE REVIEW

**Comment by wumpz** [comment]
@chrycheng The separation of deparsers and toString was intentionally. If one like to test a deparser then you have to construct the sql without it. The standard form was not done only within tests but within toString. Please leave this intact. 
For the replacement of toString call within the ExpressionDeparser you are right. That should be replaced.

**Comment by chrycheng** [comment]
Yeah I had a feeling that might be an issue :)  It's a good thing I left it till the end in its own commit.  Easily reverted.  I felt that I had to [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) out the code but I guess in this case they are two very different cases.

**Comment by chrycheng** [comment]
I disagree but it appears that PMD dislikes package-private members.  If you want, we could just expose those setters as public members and add corresponding public getters.  This seems to be the pattern for other `DeParser`s anyway.

**Comment by wumpz** [comment]
I removed this pmd check.

**Pull request merged**
