### PR TITLE
Support for ANSI SQL standard function SUBSTRING( x FROM i FOR j )

### PR DESCRIPTION
**Pull request by paxdei**
Hi, this function is part of the ANSI SQL standard, though not widely supported

My changes are actually a copy/paste from the form bp2014n2/JSqlParser

### CODE REVIEW

**Comment by wumpz** [comment]
Why are ther so many whitespace changes within your pull request? Please reduce your pull request only to the changes regarding this substring function.

**Comment by paxdei** [comment]
Sorry, I had eclipse configured to auto-remove trailing spaces on save. I now have reverted most of these white-space changes

**Comment by wumpz** [comment]
Sorry about my late answer. 

So now I got some time to integrate some stuff into JSqlParser. Could you squash your commits into one and insert your issue id into the message? So it is easier to locate changes for specific issues. Thx for improving JSqlParser

**Comment by wumpz** [comment]
already solved (different issue)

**Pull request closed without merging**
