### PR TITLE
Allow Complex Parsing of Functions

### PR DESCRIPTION
**Pull request by manticore-projects**
This PR will determine the nested brackets "(" ")" and configure the Parser in order to parse Complex Function Parameters like `to_char( a = b)` and Named Function Parameters like `trim(BOTH ' ' from 'foo bar ')` ONLY WHEN the level of nesting functions is below a threshold = 7. Although this is a configurable Parser Feature.

This massively speeds up the parser. The whole `NestedBracketsPerformanceTest` Suite takes less than 3 seconds now, with 50! iterations for the concat test.

At the same time we can parse Complex  Expression Parameters for all Functions (but only when there is no deep recursion of more than 9 levels although this detail is mood because it would not work in anyway because of the slowdown).

Fixes issues #1190 #1103

This is a **CLEAN** PR handcrafted against the latest Upstream MASTER, containing only the minimal changes.

### CODE REVIEW

**Comment by manticore-projects** [comment]
LOL! The CI server is too slow for the performance test timeouts.

**Comment by wumpz** [comment]
Building an upper boundary is quite a good idea. Could you please resolve the conflicts. I already merged your case when pr. My first changes for adaption the ValuesStatement are included as well. Maybe we could skip those MultiExpressionLists, because they are handles now by SimpleExpressonLists as well.

**Comment by manticore-projects** [comment]
Merged the latest Master Branch.

**Comment by wumpz** [comment]
So could you somehow better document, how the nesting depth is calculated or modified?

**Comment by wumpz** [comment]
BTW I check your modifications. Since complex parsing is now allowed for functions I removed FunctionWithCondParams. But now your depth of seven is not enough for multiple tests. Unfortunatly.

**Comment by manticore-projects** [comment]
> So could you somehow better document, how the nesting depth is calculated or modified?

It is a simple count of the maximum Open Bracket `(`. If there are more than 7 Open Brackets we assume deep nesting and do not allow complex parsing.

> BTW I check your modifications. Since complex parsing is now allowed for functions I removed FunctionWithCondParams. But now your depth of seven is not enough for multiple tests. Unfortunately I have problems for accepting one test.

Out of my head, I foresee a situation where you have a deep nesting on a function (without complex expressions) and one complex expression somewhere else (without deep nesting). That would fail because Complex Parsing and Deep Nesting are now mutual exclusive.

However, I kept experimenting when addressing the `CASE WHEN` expressions.
Instead of counting the Open Brackets, we can define a Nested Expression Counter in the Grammar File and increment it when ever we enter a `Primary Expression` and decrement it whenever we leave a `Primary Expression`. If this worked we would have much better granularity on when to give up `Complex Parsing`.

Please let me know your particular failing test case and I will have a look at it promptly.

**Comment by manticore-projects** [comment]
@wumpz: You have modified the Brackets Threshold for Complex Parsing from 7 to 10. Unfortunately, the 7 has been selected for a purpose:
```
old duration 1565 new duration time 6873 for SELECT concat(concat(concat(concat(concat(concat(concat(concat(concat('A','B'),'B'),'B'),'B'),'B'),'B'),'B'),'B'),'B') FROM mytbl
```
It is the point when the performance impact LOOKAHEAD amplifies too much. This was also the reason why I have had defined `timeout` for the unit tests and I would like to recommend to leave it at 2000 and not to accept any change that breaks these constraints again. (2 seconds for parsing 1 single statement is too much already).

So, can we set the Threshold back to 7 again please? I am still working on a more fine granular solution, where the nesting is determined as per expression.

**Comment by wumpz** [comment]
Understand. The problem is, you are calculating the "complexity" of a statement via running through the parenthesis. So you are taking parenthesises into account that have nothing to do with complex expressions. Somehow we should count the deepness within the productions. I don't know, if that is even possible and limit there to a level of 7 or 10.

**Comment by manticore-projects** [comment]
It is not perfect, but it solves maybe 90% of the "real life" problems.
When my PRs are merged then I would like to count the real nesting in
the Primary Expression, same as I did for the CASE statement.

Problem is really that I have so many loose ends right now because the
acceptance is a bit slow.

**Comment by wumpz** [comment]
Critics acknowledged. I try to improve.

**Comment by wumpz** [comment]
Does this case counting work for lookaheads as well? If I remember right, this case deepness was never checked, or am I wrong?

**Comment by manticore-projects** [comment]
On Wed, 2021-06-02 at 05:22 -0700, Tobias wrote:
> Does this case counting work for lookaheads as well?

Yes.

>  If I remember right, this case deepness was never checked, or am I
> wrong?
It was not needed for the cases but you see a similar preparation:

1) we have a global atomic LEVEL COUNT variable (this works well,
because the parser works strictly LL)
2) when entering a Primary Expression we count up
3) when leaving the Primary Expression we count down

This will give us the true nesting level.
We will stop for looking for Complex Expressions below a certain
threshold.

I am keen to implement and test and benchmark this better logic as soon
as everything else has been tied up.
After that we can also look again if JavaCC21 can help anything. or
not.

Cheers!

**Pull request merged**
