### PR TITLE
WIP: preparing fixes for PR.

### PR DESCRIPTION
**Pull request by wheredevel**

### CODE REVIEW

**Comment by wumpz** [comment]
So back from Holidays. 

So we are going for the huge commit, do we? Should I look at the conflicting files or do you? Whats the next step?

**Comment by wheredevel** [comment]
Hi @wumpz .
I already solved all the conflicts. The PR passes the tests.  
I saw a couple of commits you did after its submission.  
If you could merge it with the current `master` - that would be great.  
Let me know if my help is needed.

**Comment by manticore-projects** [comment]
This PR is quite old and seems to be abandoned although I spotted some very good additions about MS SQL specific Statements and Server Hints.

Is there anyone taking responsibility of that PR or should I just try to salvage the scraps? There has been a lot of good work done and it would be very sad to lose this contribution.

**Comment by manticore-projects** [comment]
This thing is dead. Please resubmit properly when there is any serious interest.

**Pull request closed without merging**
