### PR TITLE
feature/fix: parsing inserts/updates/delete within CTEs

### PR DESCRIPTION
**Pull request by nicky6s**
**Problem**
In Postgres it is valid syntax to have insert, update or delete statements appear within CTEs.

See here on https://www.postgresql.org/docs/current/sql-select.html
```
with_query_name [ ( column_name [, ...] ) ] AS [ [ NOT ] MATERIALIZED ] ( select | values | insert | update | delete )
```

e.g.
```sql
WITH inserted AS (
   INSERT INTO x (foo)
   SELECT bar FROM b
   RETURNING y
)
SELECT y
  FROM inserted;
```

The current version of the parser fails when faced with these statements as only `ParenthesedSelect`s are allowed to appear within CTEs

**Solution**
Change the `WithItem` class so that...
- `WithItem` no longer extends `ParenthesedSelect`
- Instead `WithItem` has type T where T extends the new interface `ParenthesedStatement`
- `ParenthesedSelect` implements `ParenthesedStatement`
- New classes `ParenthesedInsert` + `ParenthesedUpdate` + `ParenthesedDelete` are also implementations `ParenthesedStatement`

**Notes**
I could definitely do with some feedback on the approach Ive taken here.

I've done my best to avoid impacting any existing functionality. The method `getWithItemsList` in various classes now returns a `List<WithItem<?>>` object rather than a `List<WithItem>` object. I think this should be the most "disruptive" thing I've included.

### CODE REVIEW

**Comment by manticore-projects** [comment]
Impressive contribution, thank you already for your time and effort!
Please give me a time to digest and appreciate everything properly. We will definitely merge this eventually!

**Comment by manticore-projects** [comment]
Clean, I really do like your work! Thank you again.
Please do me 2 favors though:

1) fix the Codacy exceptions
2) for the 2 failing Gradle performance tests, please reduce the number of loops from 10 to 6 (temporarily, there is a pending PR which fixes this properly)

**Comment by manticore-projects** [comment]
Please fix the formatting, then I can merge promptly.
Run './gradlew :spotlessApply' to fix these violations.

**Comment by manticore-projects** [comment]
Thank you again!

**Comment by nicky6s** [comment]
@manticore-projects I think Ive made the changes you've asked for...

> fix the Codacy exceptions

https://github.com/JSQLParser/JSqlParser/pull/2055/commits/85d114be0d49b68d415a3464d27be4a9170bbaa3

> for the 2 failing Gradle performance tests, please reduce the number of loops from 10 to 6 (temporarily, there is a pending PR which fixes this properly)

https://github.com/JSQLParser/JSqlParser/pull/2055/commits/1de2a391ec881844257479bb3f3c8f70189f543b
> Please fix the formatting

https://github.com/JSQLParser/JSqlParser/pull/2055/commits/3f60913a3dc0757e46b46ac3e5c6de91e52f2b80


However, Im still getting a Gradle test failure...
```
NestedBracketsPerformanceTest > testDeepFunctionParameters() FAILED
    net.sf.jsqlparser.JSQLParserException at NestedBracketsPerformanceTest.java:357
        Caused by: java.util.concurrent.TimeoutException at NestedBracketsPerformanceTest.java:357

3177 tests completed, 1 failed, 18 skipped
```

It's strange because when I run `NestedBracketsPerformanceTest` locally it all runs fine
image

**Comment by manticore-projects** [comment]
> However, Im still getting a Gradle test failure...

No worries, I check/fix this from here.

**Comment by nicky6s** [comment]
@manticore-projects Thanks a lot for your help 🙇

**Pull request merged**
