### PR TITLE
Support FOR UPDATE WAIT

### PR DESCRIPTION
**Pull request by AnEmortalKid**
It looks like there's support for

SELECT FOR UPDATE OF, however, Oracle SQL has a FOR UPDATE (WAIT|NOWAIT) syntax, seen here:
https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_10002.htm#i2126016

I've added support for WAIT (integer).

### CODE REVIEW

**Comment by wumpz** [comment]
You are introducing reformatting of PlainSelect. A PR should only adress its issue. 
Nevertheless JSqlParser uses Suns standard code formatting, expanding tabs to spaces.

**Comment by AnEmortalKid** [comment]
is Codacy only looking at junit.framework.Assert (iirc that was deprecated:  "Deprecated.  Please use org.junit.Assert instead.".

**Comment by wumpz** [comment]
That is junit v3. We are using junit 4. The package is something like org.junit.

**Comment by AnEmortalKid** [comment]
Based on the imports for PlainSelect:

```
package net.sf.jsqlparser.test.select;

import junit.framework.*;
import net.sf.jsqlparser.*;
import net.sf.jsqlparser.expression.*;
import net.sf.jsqlparser.expression.operators.arithmetic.*;
import net.sf.jsqlparser.expression.operators.relational.*;
import net.sf.jsqlparser.parser.*;
import net.sf.jsqlparser.schema.*;
import net.sf.jsqlparser.statement.*;
import net.sf.jsqlparser.statement.select.*;
import org.apache.commons.io.*;

import java.io.*;
import java.util.*;

import static net.sf.jsqlparser.test.TestUtils.*;
```

It looks like it's using the wrong one (junit.framework) instead of org.junit.
`void junit.framework.TestCase.assertTrue(boolean condition)`

And TestUtils looks like it might also be using the wrong one:

```
import static junit.framework.TestCase.assertEquals;
import static junit.framework.TestCase.assertNotNull;

import java.io.StringReader;
import java.util.regex.Pattern;

import org.junit.Assert;
import org.junit.Test;

import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.expression.Expression;
import net.sf.jsqlparser.expression.OracleHint;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.select.PlainSelect;
import net.sf.jsqlparser.statement.select.Select;
import net.sf.jsqlparser.statement.select.SetOperationList;
import net.sf.jsqlparser.util.deparser.ExpressionDeParser;
import net.sf.jsqlparser.util.deparser.SelectDeParser;
import net.sf.jsqlparser.util.deparser.StatementDeParser;
```

I'll update my statements to just use assertNotNull (whatever is statically imported). 

Unless you'd like me to change the import since it might have slipped as the wrong one at some point?

**Comment by AnEmortalKid** [comment]
Ah yeah, I see I messed up the deparser. I'll get that fixed.

**Pull request merged**
