### PR TITLE
Fix issue #446

### PR DESCRIPTION
**Pull request by chrycheng**
Fixes issue #446.

### CODE REVIEW

**Comment by chrycheng** [comment]
My pleasure!  BTW, I think the Codacy rule checking for asserts in the tests should be updated to consider Mockito method invocation verifications as asserts.

**Comment by AnEmortalKid** [comment]
+1, I think we should update the codacy rules to include mockito verify

**Comment by wumpz** [comment]
Have to lock into codacy. Till now I did no configuration regarding issue types. Any clue how to do it but in addition to the assert fail check?

**Comment by chrycheng** [comment]
Sorry, no.  Not familiar with Codacy too.

**Comment by AnEmortalKid** [comment]
Let me ask at work, a friend worked with some codacy.

**Comment by AnEmortalKid** [comment]
So, coworker said no :(

However, I dug a bit into codacy and I believe it is using PMD (which is where that rule comes in). 

1. We could disable that PMD rule (bad idea).
2. We could try adding `@SuppressWarnings("PMD.JUnitTestShouldIncludeAssert")` on the tests that need verifies. (could work).
3. We could combine the warning suppression and one of us could write a custom PMD rule to check that there's a mockito.verify if that rule is excluded (i looked a bit into rules, it would take some time)

**Comment by wumpz** [comment]
It seems to be an open issue for pmd at least for Mockitos verify.

**Pull request merged**
