### PR TITLE
Fix issue 2090: Correctly parse LOCK clause in ALTER TABLE statements

### PR DESCRIPTION
**Pull request by minleejae**
# Summary
This PR addresses issue #2090 by adding support for parsing the LOCK clause in ALTER TABLE statements in JSQLParser. Previously, the LOCK=NONE clause was incorrectly parsed as UNSPECIFIC, causing ambiguity in the interpretation of certain ALTER TABLE statements.

# Changes
Updated AlterOperation enum to include LOCK.
Modified the parser to correctly identify and handle the LOCK clause.

### CODE REVIEW

**Comment by manticore-projects** [comment]
Greetings! Looks very clean, fantastic job! Thank you for your contribution, I will merge promptly when QA/CI tests have passed! Kudos.

**Comment by manticore-projects** [comment]
Please, run './gradlew :spotlessApply' to fix these violations.

**Comment by minleejae** [comment]
@manticore-projects 

Hi, I’m working on a personal project involving MySQL DDL, and I’ve encountered several DDL statements that are not being parsed correctly. I’m actively working on fixing as many of these issues as I can. I was wondering if you have any plans for the release date of version 5.1? I’d like to contribute as much as possible before the 5.1 release.

Thank you!

**Comment by manticore-projects** [comment]
Greetings to Seoul and welcome!

I personally have only little interest in DDL outside of Oracle. So you contribution is most welcome and appreciated! Keep sending please!

All the best and cheers!
(I miss Korea so much!)

**Comment by manticore-projects** [comment]
Release Date for 5.1 is likely around December/January. No fixed plans, we do it when we have time.

**Pull request merged**
