### PR TITLE
JSQLPARSER-584: adds support for MySQL (a,b,...)OP(c,d,...) expression

### PR DESCRIPTION
**Pull request by adriil**
Fixes issue #584

### CODE REVIEW

**Comment by adriil** [comment]
I'll add the missing tests as soon as possible.

**Comment by adriil** [comment]
I realize that I could get rid of my new class, which is useless, actually, as it only contains an expressionList...
I will rework my PR, do you want me to add commit here once it's done, or to close this one and provide a new clean PR ?

**Comment by wumpz** [comment]
Modify this pr. I will make s squash merge at the end, if you don't mind.

**Comment by adriil** [comment]
Hi,
Sorry for the silence, I had busy days last week.

Actually I'm facing an issue.
In order to get rid of my class which just contains an expressionList, I tried to use directly the expressionList as a ComparisonItem, instead of my class. But It can't be done because the ExpressionList is not regarded as an Expression itself.
I felt dumb because I already faced this issue, this was the reason I've created a class implementing Expression to get through this.
A solution to me, without creating useless class, would be to make ExpressionList implementing Expression, like a Composite. But this may be a big step as almost everything relies on Expression and ExpressionList.

**Comment by wumpz** [comment]
Hmm. Same here. Leave your class. Rename it to ValueListExpression and everything is fine, at least regarding this pull request.

**Pull request merged**
