### PR TITLE
support FILTER not only for window function

### PR DESCRIPTION
**Pull request by tvar**
**FILTER** expression can be applied to aggregate functions, not only **WINDOW**-functions.
Support query like
```SQL 
select max(f1) filter(where f2>0) from t1
```

[https://www.postgresql.org/docs/current/sql-expressions.html]()
```
aggregate_name (expression [ , ... ] [ order_by_clause ] ) [ FILTER ( WHERE filter_clause ) ]
```

Also fix https://github.com/JSQLParser/JSqlParser/issues/934

### CODE REVIEW

**Review by AnEmortalKid — APPROVED** [review]

**Comment by wumpz** [comment]
Any progress here?

**Comment by tvar** [comment]
What progress do you expect? What can I do to make you accept this PR?

**Comment by wumpz** [comment]
Hi,
You made a star import out of some fixed imports. Please rewind this.Cheers Tobias
-------- Ursprüngliche Nachricht --------Von: Роман Зотов <notifications@github.com> Datum: 05.10.20  08:38  (GMT+01:00) An: JSQLParser/JSqlParser <JSqlParser@noreply.github.com> Cc: Tobias <t.warneke@gmx.net>, Comment <comment@noreply.github.com> Betreff: Re: [JSQLParser/JSqlParser] support FILTER not only for window
  function (#1046) 
What progress do you expect? What can I do to make you accept this PR?

**Comment by tvar** [comment]
Fixed.

**Pull request merged**
