### PR TITLE
bugfix #720 #991: supporting SELECT "conditions"

### PR DESCRIPTION
**Pull request by mo3000**
As it is in the issues above, sqls below won't parse.
```sql
SELECT column IS NOT NULL FROM table;
SELECT 0 IS NULL;
```
Then I figured out that in function `SelectExpressionItem()` -> `SimpleExpression()` should be replaced by `Condition()` since null expression, bool expression and SimpleExpression itself are handled in `Condition()`.
Because function `PivotSingleInItems()` also use `SelectExpressionItem()`, I copyed the original `SelectExpressionItem()` so that the "pivot" test doesn't break.

All tests passed, but "SELECT 1 < 2 AS a, (0 IS NULL) AS b" won't work because something is wrong with aliasing an  expression with parentheses. 
"SELECT (1 < 2) AND (3 < 4)" won't work too, I belive this can be fixed somehow in function `Condition()`.

### CODE REVIEW

**Comment by wumpz** [comment]
Did you run all tests? I had a similar approach and the performance dropped significantly.

**Comment by mo3000** [comment]
I run "mvn test" before and after this pr. 
Before:
```[INFO] Total time:  01:17 min```
After:
```[INFO] Total time:  01:16 min```
I tried several times, running time is around 1:20 on my mac (open jdk 14), no performance dropped. mvn says "[INFO] BUILD SUCCESS" , is there anything I should run specifically?

**Comment by wumpz** [comment]
Strange, but very fortunate. Maybe some of the recent changes corrected this behaviour.

**Comment by wumpz** [comment]
The test on my machine is nearly 50% slower with your modification. Strange that you did not experience such a performance drop.

**Comment by wumpz** [comment]
Now I modified some productions and gained more speed. Nearly the same as before.

**Comment by mo3000** [comment]
teriffic! I'll try that on my machine.

**Pull request merged**
