### PR TITLE
INSERT with SetOperations

### LINKED ISSUE #1491: can not parser union select clause in insert  query
I mock a simple insert query like this
 insert into table1 (tf1,tf2,tf2)
((select sf1,sf2,sf3 from s1) union (select rf1,rf2,rf2 from r1)) 
and get  follow paseexception:
net.sf.jsqlparser.JSQLParserException: Encountered unexpected token: "union" "UNION"
    at line 2, column 31.
Was expecting one of:

    "&"
    ")"
    ","
    "::"
    "<<"
    ">>"
    "COLLATE"
    "["
    "^"
    "|"

	net.sf.jsqlparser.parser.CCJSqlParserUtil.parseStatement(CCJSqlParserUtil.java:190)
	net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:63)
	net.sf.jsqlparser.parser.CCJSqlParserUtil.parse(CCJSqlParserUtil.java:38)

**System**
 - Postgresql
- Java 1.8
- JSqlParser 4.2

### PR DESCRIPTION
**Pull request by manticore-projects**
Simplify the INSERT production
Use SetOperations for Select and Values
Better Bracket handling for WITH ... SELECT ...
Fixes #1491

Following statements will work now:
```sql
(
    with a as (select * from dual) 
    select * from a
);

insert into table1 (tf1,tf2,tf2) (   
    (select sf1,sf2,sf3 from s1)
    union (select rf1,rf2,rf2 from r1)
);
```

### CODE REVIEW

**Comment by wumpz** [comment]
please resolve conflicts

**Comment by wumpz** [comment]
After merging I am not able to compile anymore.

**Comment by manticore-projects** [comment]
> After merging I am not able to compile anymore.

What is the challenge please?
Have you tried `gradle build`? The CI passed before.

**Comment by manticore-projects** [comment]
Confirmed, I get the same problem -- very strange. How did the CI succeed?
I will fix that tomorrow morning, whatever it is.

**Comment by wumpz** [comment]
I am not able to correct this since 
```
Select SelectWithWithItems( ):
{
    Select select;
    List<WithItem> with = null;
}
{
    LOOKAHEAD(2) ( 
        "(" with=WithList()  select = Select( with ) ")" { select.withUsingWithBrackets(true); }
    )
    |
    (
         [ with=WithList() ] select = Select( with )
    )

    {
        return select;
    }
}
```

yields 

```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project jsqlparser: Compilation failure: Compilation failure: 
/C:/work/java/JSqlParser/target/generated-sources/javacc/net/sf/jsqlparser/parser/CCJSqlParser.java:[5631,9] unreachable statement
/C:/work/java/JSqlParser/target/generated-sources/javacc/net/sf/jsqlparser/parser/CCJSqlParser.java:[5639,1] missing return statement
-> [Help 1]
```

This one I know from switching to modern JavaCC templating. Very strange.

**Comment by wumpz** [comment]
I pushed a running version. To get this state I had to remove the changes from 

SelectWithWithItems production 
and disabled tests in InsrtTest (testInsertOutputClause, one assert in testInsertWithSelect)

**Comment by wumpz** [comment]
Here only the Codacy and Merge checks were presented. Your change was perfectly mergeable, but this means not automatically compilable.

**Comment by wumpz** [comment]
Corrected grammar. It was semantically incomplete.

**Comment by wumpz** [comment]
1. Tests reactivated again.
2. deparser and toString for OutputClause implemented

so this seems to be complete now

**Comment by manticore-projects** [comment]
Good Morning,

thank you for sorting this out. I am really sorry for this mess, no idea what happened.
I build and test every single time, before I push -- however, checking out this PR, I found those missing part myself and was able to reproduce the problem. Very odd. I can only imagine, that I merged wrongly when resolving conflicts after the previous PR has been accepted.

Sorry again and cheers!

**Comment by manticore-projects** [comment]
> Maybe its time to switch to Github Actions.

Yes please, I'd like to support that, because I really do not like it when things suddenly stop to work -- without notice.
This commit should have been rejected and sent me a message at least.

**Pull request merged**
