### PR TITLE
Assorted fixes to the Java CC Parser definition

### PR DESCRIPTION
**Pull request by manticore-projects**
Implement Oracle Hints for INSERT, UPDATE, MERGE, DELETE

### CODE REVIEW

**Review by wumpz — APPROVED** [review]
Looks good. Thx for the changes. Next time try to keep one improvement in one PR.

**Comment by manticore-projects** [comment]
> Next time try to keep one improvement in one PR.

Actually I split it on purpose because I was not too sure how you would like the Oracle specific change. I did not want to jeopardize the simple correction waiting in the queue.

Thank you for merging and best regards
Viele Gruesse aus Thailand.

**Comment by wumpz** [comment]
If you use the syntax **fixes #id** then Github will automatically close this issue.

**Comment by wumpz** [comment]
And: viele Grüße zurück ...

**Pull request merged**
