### PR TITLE
Fix issue in parsing TRY_CAST() function

### PR DESCRIPTION
**Pull request by prashantcsutar**
MR request for issue #1390 Unable to parse snowflake's TRY_CAST() function

### CODE REVIEW

**Comment by prashantcsutar** [comment]
Hi @manticore-projects ,

Can you please review this PR again? I have changes the implementation as suggested by you. Please let me know if its till needs any changes.

Best Regards,
Prashant

**Comment by manticore-projects** [comment]
Thank you, it looks good to me and nicely done.
However, only @wumpz can decide about the final adoption. This may take a few days.

**Comment by prashantcsutar** [comment]
Hi @wumpz , @manticore-projects , 
This fix is important for our project. Could you please merge it so that it will become part of `4.3` release?
Best Regards,
Prashant

**Comment by manticore-projects** [comment]
Greetings.

Noted, we will see what we can do. @wumpz is author and owner of the software and only he can merge. I would be able to assist you with a Snapshot JAR if this helped anything.

**Comment by wumpz** [comment]
Sorry for being late with mergine. You know, there is some other stuff to do. However, your PR looks good.

**Comment by wumpz** [comment]
I will deploy an actual snapshot during the next few hours.

**Comment by prashantcsutar** [comment]
Hi @wumpz , Thanks a lot for merging this PR.

**Pull request merged**
