### PR TITLE
#1401 add junit-jupiter-api

### PR DESCRIPTION
**Pull request by gitmotte**
#1401

### CODE REVIEW

**Comment by wumpz** [comment]
So you are simply replacing this jar which is using the vintage engine to run the junit 4 tests we have now? Or are you going to replace all annotations and used classes to the jupiter version?

**Comment by gitmotte** [comment]
Not at all, this is just a bugfix for a missing dependency in Maven's pom.xml  
Please have a look at this comment https://github.com/JSQLParser/JSqlParser/issues/1401#issuecomment-961732746

**Comment by wumpz** [comment]
Sorry. I see that within some of the former PRs there was this change so JSqlParser now indeed uses some kind of mixture.

**Comment by wumpz** [comment]
However, I will change the import to be proper for this case.

**Comment by manticore-projects** [comment]
The JUnit 5 dependency was brought in by me for allowing parallel tests with Gradle. Forgetting to add it to Maven was an oversight. (I never liked Maven and jumped from ANT to GRADLE directly).

That said, I think it would make sense to migrate to JUnit 5 and to drop JUnit 4 eventually.

**Comment by wumpz** [comment]
No problem here. I had the same problematic in diff rent other projects. You have to check that your tests are running. If wrongly configured,. Junjt 4 or 5 tests are skipped.

However, with this knowledge I consider this my problem, since I did not see the chance before.

**Comment by wumpz** [comment]
Look into #1427.

**Pull request merged**
